### ISSUE TITLE
Wrong code or bug?

### ISSUE THREAD

**Issue by Adrone-Pogi** [GabBiswajit/Lifesteal#2]
when i killed someone they're supposed to lose 1 heart but instead they lost 9 hearts shouldn't be -1 heart not -9 hearts

**Comment by GabBiswajit** [comment]
Check your config

**Comment by Adrone-Pogi** [comment]
> Check your config

How should i edit it?

**Comment by GabBiswajit** [comment]
Go on plugin data than lifesteal than `config.yml`and take a screenshot and send to me

**Comment by Adrone-Pogi** [comment]
![Uploading Screenshot_20230825_235818.jpg…]()

**Comment by GabBiswajit** [comment]
Image can't load

**Comment by Adrone-Pogi** [comment]
Ohh add me on discord then .envyyz_

**Comment by Adrone-Pogi** [comment]
![Uploading Screenshot_20230825_235818.jpg…]()

**Comment by GabBiswajit** [comment]
Fix #
