### ISSUE TITLE
Lifesteal Bug

### ISSUE THREAD

**Issue by R4bbit36** [GabBiswajit/Lifesteal#5]
there is a bug where u get banned/lost your all hearts and then quickly log out the server and rejoin then the hearts get duplicated 😓 

Pls fix this bug🙏

**Comment by GabBiswajit** [comment]
Thanks for reporting we fix it soon as possible

**Comment by GabBiswajit** [comment]
I have a question @R4bbit36 if the player get ban than how he/she do rejoin ?

**Comment by GabBiswajit** [comment]
Fix #8

**Comment by R4bbit36** [comment]
Player rejoins simply by logging soon after got banned and join normally as
usual they do and get un banned 5 free  hearts
